#Config name is config.yml
#Everything is automated by main file
#Server below is DiscordBots Server
'110373943822540800':  # Server ID
  clear: 100  # Amount cleared by default on clear command
  default_roles: []  # Roles given to new users
  disabled: []  #  Channels where the bot ignores everything
  mod_log: ''  # Channel where the bot logs mod commands (not yet implemented)
  disabled_commands: []  # Commands disabled in the server
  prefix: "'"   # Command prefix for this server
  silent:  # Channels where bot ignores un-prefixed triggers
  - '110373943822540800'
  - '110374153562886144'
  - '116705171312082950'
  - '117018340114825217'
  - '132632676225122304'
  - '113743192305827841'

blacklist: []  # Global blacklist

